# repos.yaml
# Specify TERRAGRUNT_TFPATH environment variable to accomodate setting --default-tf-version
repos:
- id: "/.*/"
  workflow: terragrunt
workflows:
  terragrunt:
    plan:
      steps:
      - env:
          name: TERRAGRUNT_TFPATH
          command: 'echo "terraform${ATLANTIS_TERRAFORM_VERSION}"'
      # The COMMENT_ARGS here allows a comment of `atlantis plan -- -destroy`
      # in order to destroy a particular config.
      # https://github.com/runatlantis/atlantis/pull/1565
      - run: terragrunt plan -no-color $(eval echo ${COMMENT_ARGS}) -out=${PLANFILE}
    apply:
      steps:
      - env:
          name: TERRAGRUNT_TFPATH
          command: 'echo "terraform${ATLANTIS_TERRAFORM_VERSION}"'
      - run: terragrunt apply -no-color $PLANFILE